apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-microservice
  labels:
    app: eureka-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-microservice
  template:
    metadata:
      labels:
        app: eureka-microservice
    spec:
      containers:
        - name: eureka-microservice
          image: juanhoyos/microservice:eureka-v1
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"